name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file=dev.tfvars

    - name: Terraform Apply (Test Environment)
      if: github.event_name == 'pull_request'
      run: terraform apply -auto-approve -var-file=dev.tfvars

    - name: Terraform Apply (Production)
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -var-file=prod.tfvars

    - name: Cleanup Test Environment
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      run: terraform destroy -auto-approve -var-file=dev.tfvars
